#!/bin/bash
# scripts/demo/init.sh
#
# v1.3.35 demo-stack initializer. Materialises ~/argos-demo/ with the
# base compose file + demo override + Caddyfile + crowdsec/* bind-
# mount sources, generates a fresh .env with random secrets, brings
# the stack up, runs `argos demo seed`, and prints the access URL.
#
# Idempotent: running it twice on a populated demo stack is a no-op
# (compose detects no diff; demo seed CLI uses INSERT OR IGNORE).
#
# Zero impact on argos-prod by construction:
#   - separate container names (argos-demo-*)
#   - separate volume names    (argos_demo_*)
#   - separate network         (argos-demo-net)
#   - separate host ports      (9181 panel, 127.0.0.1:8090 caddy)
#
# Pre-flight refuses to run if argos-prod-argos:1.3.35 is missing
# (operator must run `make build-prod-image` first).

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DEMO_DIR="${ARGOS_DEMO_DIR:-${HOME}/argos-demo}"
ARGOS_VERSION="$(grep -oE 'argosVersion = "[^"]+"' "${REPO_DIR}/backend/cmd/argos/main.go" | head -1 | cut -d'"' -f2)"
EXPECTED_IMAGE="argos-prod-argos:${ARGOS_VERSION}"

log()  { printf '[demo/init] %s\n' "$*"; }
fail() { printf '[demo/init] FAIL: %s\n' "$*" >&2; exit 1; }

# Pre-flight
[ -d "${REPO_DIR}/crowdsec" ] || fail "missing ${REPO_DIR}/crowdsec (not an argos-edge checkout?)"
docker compose ps >/dev/null 2>&1 || fail "docker compose unavailable"

if ! docker images "${EXPECTED_IMAGE}" --format '{{.ID}}' | grep -q .; then
    fail "image ${EXPECTED_IMAGE} missing -- run 'make build-prod-image' first (in ${REPO_DIR})"
fi

log "demo-dir: ${DEMO_DIR}"
log "image:    ${EXPECTED_IMAGE}"

# Materialise ~/argos-demo/
mkdir -p "${DEMO_DIR}"
cp "${REPO_DIR}/docker-compose.yml"     "${DEMO_DIR}/docker-compose.yml"
cp "${REPO_DIR}/Caddyfile"              "${DEMO_DIR}/Caddyfile"
cp "${REPO_DIR}/scripts/demo/docker-compose.override.yml" "${DEMO_DIR}/docker-compose.override.yml"
# crowdsec/* bind-mount sources (read-only mounts in the compose).
rm -rf "${DEMO_DIR}/crowdsec"
cp -r "${REPO_DIR}/crowdsec"            "${DEMO_DIR}/crowdsec"

# Generate .env with random secrets if not already present. Demo .env
# is ephemeral -- never committed, regenerated on every fresh init.
if [ ! -f "${DEMO_DIR}/.env" ]; then
    SESSION_SECRET="$(openssl rand -hex 32)"
    MASTER_KEY="$(openssl rand -hex 32)"
    cat > "${DEMO_DIR}/.env" <<EOF
# argos-demo .env -- generated by scripts/demo/init.sh
# Regenerated on every fresh init; never commit this file.

ARGOS_SESSION_SECRET=${SESSION_SECRET}
ARGOS_MASTER_KEY=${MASTER_KEY}
ARGOS_INITIAL_ADMIN_USER=demo
ARGOS_INITIAL_ADMIN_PASSWORD=demo1234
ARGOS_PANEL_MODE=lan
CLOUDFLARE_API_TOKEN=
CROWDSEC_BOUNCER_API_KEY=demo-bouncer-key-not-real
EOF
    chmod 600 "${DEMO_DIR}/.env"
    log "generated ${DEMO_DIR}/.env (admin: demo / demo1234)"
else
    log "${DEMO_DIR}/.env already present, leaving as-is"
fi

# Bring the demo stack up. The override.yml has top-level "name:
# argos-demo" so compose project naming is deterministic regardless
# of cwd.
log "docker compose up -d (project=argos-demo)..."
( cd "${DEMO_DIR}" && docker compose up -d --no-deps argos crowdsec caddy )

# Wait for the panel to come up (the /healthz handler is the gate).
log "waiting for argos-demo-panel healthcheck..."
for i in $(seq 1 60); do
    health="$(docker inspect argos-demo-panel --format '{{.State.Health.Status}}' 2>/dev/null || echo "starting")"
    if [ "${health}" = "healthy" ]; then
        break
    fi
    sleep 1
done
[ "${health}" = "healthy" ] || fail "argos-demo-panel did not reach healthy state in 60s (got ${health})"

# Seed panel DB. The triple safety gates inside the seed CLI mean
# this is also safe to invoke from the host shell on a misconfigured
# system: --yes + ARGOS_DEMO_SEED=1 + path-doesn't-contain-argos-prod.
log "seeding panel DB (10 surfaces)..."
docker exec -e ARGOS_DEMO_SEED=1 argos-demo-panel /argos demo seed --yes

# Seed CrowdSec LAPI with synthetic banned IPs (RFC5737). The panel's
# Banned IPs tab + Threats page read from LAPI directly, so this
# populates that surface. cscli is in the crowdsec image; --reason
# carries the demo: marker for the operator's audit trail.
log "seeding LAPI with demo banned IPs..."
DEMO_BANNED_IPS=(
    "192.0.2.7"   "192.0.2.13"  "192.0.2.55"  "192.0.2.99"
    "198.51.100.7" "198.51.100.13" "198.51.100.55"
    "203.0.113.5" "203.0.113.42" "203.0.113.99"
)
for ip in "${DEMO_BANNED_IPS[@]}"; do
    docker exec argos-demo-crowdsec cscli decisions add \
        --ip "${ip}" --duration 168h --reason "demo: synthetic ban" \
        >/dev/null 2>&1 || true
done
log "  $((${#DEMO_BANNED_IPS[@]})) banned IPs added to LAPI"

cat <<EOF

==================================================================
  demo stack ready

  panel:    http://localhost:9181
  login:    demo / demo1234
  caddy:    http://localhost:8090   (LAN-side proxy, optional)

  containers: docker compose -p argos-demo ps
  teardown:   ${REPO_DIR}/scripts/demo/teardown.sh

  argos-prod stack untouched (separate containers + volumes + network).
==================================================================

EOF
