#!/bin/bash
# scripts/demo/init.sh
#
# v1.3.35 demo-stack initializer. Materialises ~/argos-demo/ with the
# base compose file + demo override + Caddyfile + crowdsec/* bind-
# mount sources, generates a fresh .env with random secrets, brings
# the stack up, runs `argos demo seed`, and prints the access URL.
#
# Idempotent: running it twice on a populated demo stack is a no-op
# (compose detects no diff; demo seed CLI uses INSERT OR IGNORE).
#
# Zero impact on argos-prod by construction:
#   - separate container names (argos-demo-*)
#   - separate volume names    (argos_demo_*)
#   - separate network         (argos-demo-net)
#   - separate host ports      (9181 panel, 127.0.0.1:8090 caddy)
#
# Pre-flight refuses to run if argos-prod-argos:1.3.35 is missing
# (operator must run `make build-prod-image` first).

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DEMO_DIR="${ARGOS_DEMO_DIR:-${HOME}/argos-demo}"
ARGOS_VERSION="$(grep -oE 'argosVersion = "[^"]+"' "${REPO_DIR}/backend/cmd/argos/main.go" | head -1 | cut -d'"' -f2)"
EXPECTED_IMAGE="argos-prod-argos:${ARGOS_VERSION}"

log()  { printf '[demo/init] %s\n' "$*"; }
fail() { printf '[demo/init] FAIL: %s\n' "$*" >&2; exit 1; }

# Pre-flight
[ -d "${REPO_DIR}/crowdsec" ] || fail "missing ${REPO_DIR}/crowdsec (not an argos-edge checkout?)"
docker compose ps >/dev/null 2>&1 || fail "docker compose unavailable"

if ! docker images "${EXPECTED_IMAGE}" --format '{{.ID}}' | grep -q .; then
    fail "image ${EXPECTED_IMAGE} missing -- run 'make build-prod-image' first (in ${REPO_DIR})"
fi

log "demo-dir: ${DEMO_DIR}"
log "image:    ${EXPECTED_IMAGE}"

# Materialise ~/argos-demo/
mkdir -p "${DEMO_DIR}"
cp "${REPO_DIR}/docker-compose.yml"     "${DEMO_DIR}/docker-compose.yml"
cp "${REPO_DIR}/Caddyfile"              "${DEMO_DIR}/Caddyfile"
cp "${REPO_DIR}/scripts/demo/docker-compose.override.yml" "${DEMO_DIR}/docker-compose.override.yml"
# crowdsec/* bind-mount sources (read-only mounts in the compose).
rm -rf "${DEMO_DIR}/crowdsec"
cp -r "${REPO_DIR}/crowdsec"            "${DEMO_DIR}/crowdsec"

# Generate .env with random secrets if not already present. Demo .env
# is ephemeral -- never committed, regenerated on every fresh init.
if [ ! -f "${DEMO_DIR}/.env" ]; then
    SESSION_SECRET="$(openssl rand -hex 32)"
    MASTER_KEY="$(openssl rand -hex 32)"
    cat > "${DEMO_DIR}/.env" <<EOF
# argos-demo .env -- generated by scripts/demo/init.sh
# Regenerated on every fresh init; never commit this file.

ARGOS_SESSION_SECRET=${SESSION_SECRET}
ARGOS_MASTER_KEY=${MASTER_KEY}
ARGOS_INITIAL_ADMIN_USER=demo
ARGOS_INITIAL_ADMIN_PASSWORD=demo1234
ARGOS_PANEL_MODE=lan
CLOUDFLARE_API_TOKEN=
CROWDSEC_BOUNCER_API_KEY=demo-bouncer-key-not-real
EOF
    chmod 600 "${DEMO_DIR}/.env"
    log "generated ${DEMO_DIR}/.env (admin: demo / demo1234)"
else
    log "${DEMO_DIR}/.env already present, leaving as-is"
fi

# Bring the demo stack up. The override.yml has top-level "name:
# argos-demo" so compose project naming is deterministic regardless
# of cwd.
#
# v1.3.35.3 fix: pre-1.3.35.3 used `up -d --no-deps argos crowdsec
# caddy` which bypassed the crowdsec-init sidecar. That sidecar
# runs `cscli machines add argos-panel` which writes machine
# credentials the panel imports on first boot; without it every
# panel-to-LAPI call returns 403 (country reconciler, threats UI,
# AppSec metrics, etc.). The compose `depends_on` chain
# (argos -> crowdsec-init: service_completed_successfully) handles
# ordering automatically -- letting compose bring the full stack
# up makes the init sidecar run + complete before the panel
# starts.
log "docker compose up -d (project=argos-demo, full stack)..."
( cd "${DEMO_DIR}" && docker compose up -d )

# Wait for the panel to come up. The compose depends_on chain
# blocks panel start on crowdsec-init: service_completed_successfully,
# so the panel container reaches "starting" only after init has
# written the credentials. Bump the timeout to 120s to cover
# the init step's add-machine call + first-time hub-update.
log "waiting for argos-demo-panel healthcheck (incl. crowdsec-init)..."
for i in $(seq 1 120); do
    health="$(docker inspect argos-demo-panel --format '{{.State.Health.Status}}' 2>/dev/null || echo "starting")"
    if [ "${health}" = "healthy" ]; then
        break
    fi
    sleep 1
done
[ "${health}" = "healthy" ] || fail "argos-demo-panel did not reach healthy state in 120s (got ${health})"

# Confirm crowdsec-init exited cleanly (its job was to register the
# argos-panel machine and drop credentials in /shared/). exit 0 =
# credentials written; exit non-zero = something blocked machine
# registration and the panel will see 403s on LAPI.
init_exit="$(docker inspect argos-demo-crowdsec-init --format '{{.State.ExitCode}}' 2>/dev/null || echo "?")"
if [ "${init_exit}" != "0" ]; then
    log "WARN: argos-demo-crowdsec-init exit code = ${init_exit} (expected 0)"
    docker logs argos-demo-crowdsec-init 2>&1 | tail -10 || true
fi

# Wait for the panel to import the machine credentials. The
# bootstrap reconciler reads /data/shared/crowdsec-machine-
# credentials.yaml, encrypts the password into settings, and
# deletes the sentinel file. ~5-10s on a healthy boot.
log "waiting for panel to import LAPI machine credentials..."
for i in $(seq 1 30); do
    if docker exec argos-demo-crowdsec cscli machines list 2>/dev/null | grep -q "argos-panel"; then
        log "  PASS: argos-panel machine registered + visible to LAPI"
        break
    fi
    sleep 1
done

# Seed panel DB. The triple safety gates inside the seed CLI mean
# this is also safe to invoke from the host shell on a misconfigured
# system: --yes + ARGOS_DEMO_SEED=1 + path-doesn't-contain-argos-prod.
log "seeding panel DB (10 surfaces)..."
docker exec -e ARGOS_DEMO_SEED=1 argos-demo-panel /argos demo seed --yes

# Seed CrowdSec LAPI with synthetic banned IPs (RFC5737). The panel's
# Banned IPs tab + Threats page read from LAPI directly, so this
# populates that surface. cscli is in the crowdsec image; --reason
# carries the demo: marker for the operator's audit trail. v1.3.35.2:
# expanded from 10 to 100 IPs across realistic scenario distribution.
log "seeding LAPI with demo banned IPs (100 IPs across scenarios)..."

# Scenario distribution mirrors what a real argos prod deployment
# would accumulate over a few days of public exposure:
#   ~30 CAPI community blocklist (origin=CAPI)
#   ~25 cscli http-bf / probing / ssh-bf etc.
#   ~15 AppSec WAF blocks (sql_injection, xss, lfi, rce, anomaly)
#   ~30 generic "demo: synthetic ban"
seed_lapi_decision() {
    local ip="$1" reason="$2" duration="$3"
    docker exec argos-demo-crowdsec cscli decisions add \
        --ip "${ip}" --duration "${duration}" --reason "${reason}" \
        >/dev/null 2>&1 || true
}

# Generate 100 RFC5737 IPs spread across the three blocks
# (192.0.2.x, 198.51.100.x, 203.0.113.x). 30 CAPI + 25 cscli scenarios
# + 15 AppSec WAF + 30 generic.
declare -a SEEDS_CAPI SEEDS_CSCLI SEEDS_APPSEC SEEDS_GENERIC

# CAPI samples (community blocklist)
for i in $(seq 1 30); do
    octet=$(( (i * 7 + 3) % 254 + 1 ))
    SEEDS_CAPI+=("192.0.2.${octet}")
done

# cscli scenarios (mix of http-bf, http-probing, ssh-bf, http-cve, http-sensitive-files)
SCENARIOS_CSCLI=(
    "crowdsecurity/http-bf"
    "crowdsecurity/http-bf"
    "crowdsecurity/http-bf"
    "crowdsecurity/http-bf"
    "crowdsecurity/http-bf"
    "crowdsecurity/http-bf"
    "crowdsecurity/http-bf"
    "crowdsecurity/http-bf"
    "crowdsecurity/http-bf"
    "crowdsecurity/http-bf"
    "crowdsecurity/http-probing"
    "crowdsecurity/http-probing"
    "crowdsecurity/http-probing"
    "crowdsecurity/http-probing"
    "crowdsecurity/http-probing"
    "crowdsecurity/http-probing"
    "crowdsecurity/http-probing"
    "crowdsecurity/http-probing"
    "crowdsecurity/ssh-bf"
    "crowdsecurity/ssh-bf"
    "crowdsecurity/ssh-bf"
    "crowdsecurity/ssh-bf"
    "crowdsecurity/ssh-bf"
    "crowdsecurity/http-cve-probing"
    "crowdsecurity/http-cve-probing"
)
for i in $(seq 0 24); do
    octet=$(( (i * 11 + 17) % 254 + 1 ))
    SEEDS_CSCLI+=("198.51.100.${octet}|${SCENARIOS_CSCLI[i]}")
done

# AppSec WAF (sql_injection, xss, lfi, rce, anomaly)
APPSEC_REASONS=(
    "sql_injection" "sql_injection" "sql_injection" "sql_injection" "sql_injection"
    "xss" "xss" "xss"
    "lfi" "lfi" "lfi"
    "rce" "rce"
    "appsec_anomaly" "appsec_anomaly"
)
for i in $(seq 0 14); do
    octet=$(( (i * 13 + 29) % 254 + 1 ))
    SEEDS_APPSEC+=("203.0.113.${octet}|${APPSEC_REASONS[i]}")
done

# Generic (synthetic baseline)
for i in $(seq 0 29); do
    block=$(( i % 3 ))
    octet=$(( (i * 17 + 41) % 254 + 1 ))
    case ${block} in
        0) SEEDS_GENERIC+=("192.0.2.${octet}") ;;
        1) SEEDS_GENERIC+=("198.51.100.${octet}") ;;
        2) SEEDS_GENERIC+=("203.0.113.${octet}") ;;
    esac
done

# Apply in parallel batches of 10 to keep total time reasonable.
# `wait` after each batch is the synchronization point.
batch_count=0
for ip in "${SEEDS_CAPI[@]}"; do
    seed_lapi_decision "${ip}" "demo: capi community blocklist" "168h" &
    batch_count=$((batch_count+1))
    if [ ${batch_count} -ge 10 ]; then wait; batch_count=0; fi
done
wait
batch_count=0
for entry in "${SEEDS_CSCLI[@]}"; do
    ip="${entry%%|*}"; scenario="${entry##*|}"
    seed_lapi_decision "${ip}" "demo: ${scenario}" "168h" &
    batch_count=$((batch_count+1))
    if [ ${batch_count} -ge 10 ]; then wait; batch_count=0; fi
done
wait
batch_count=0
for entry in "${SEEDS_APPSEC[@]}"; do
    ip="${entry%%|*}"; reason="${entry##*|}"
    seed_lapi_decision "${ip}" "demo: appsec ${reason}" "24h" &
    batch_count=$((batch_count+1))
    if [ ${batch_count} -ge 10 ]; then wait; batch_count=0; fi
done
wait
batch_count=0
for ip in "${SEEDS_GENERIC[@]}"; do
    seed_lapi_decision "${ip}" "demo: synthetic ban" "168h" &
    batch_count=$((batch_count+1))
    if [ ${batch_count} -ge 10 ]; then wait; batch_count=0; fi
done
wait

total_lapi=$(( ${#SEEDS_CAPI[@]} + ${#SEEDS_CSCLI[@]} + ${#SEEDS_APPSEC[@]} + ${#SEEDS_GENERIC[@]} ))
log "  ${total_lapi} banned IPs added to LAPI (CAPI=${#SEEDS_CAPI[@]} cscli=${#SEEDS_CSCLI[@]} appsec=${#SEEDS_APPSEC[@]} generic=${#SEEDS_GENERIC[@]})"

cat <<EOF

==================================================================
  demo stack ready

  panel:    http://localhost:9181
  login:    demo / demo1234
  caddy:    http://localhost:8090   (LAN-side proxy, optional)

  containers: docker compose -p argos-demo ps
  teardown:   ${REPO_DIR}/scripts/demo/teardown.sh

  argos-prod stack untouched (separate containers + volumes + network).
==================================================================

EOF
