#!/bin/bash
# scripts/sync-prod.sh
#
# Sync the argos-edge source-of-truth repo into the operational
# directory the homelab operator's docker compose runs from.
# Documented in docs/operations/deployment.md.
#
# Why this exists: argos-edge supports a dual-dir homelab pattern
# where ~/argos-edge/ is the git checkout (where releases land
# via git pull) and a separate dir (typically ~/argos-prod/)
# holds the operational docker-compose.yml + .env + override
# file. The crowdsec/* and Caddyfile bind-mounts read from the
# operational dir at container runtime, so a release that
# touches setup-appsec.sh or appsec-configs is INVISIBLE to the
# running stack until those files reach the operational dir.
# v1.3.25's prod-smoke caught this; v1.3.26 ships this script.
#
# Behaviour:
#   - Diff-first preview (operator sees what's about to change).
#   - rsync with explicit denylist (operator-managed files +
#     build artefacts excluded; everything else mirrored).
#   - --delete to keep removals from upstream propagating, BUT
#     scoped to the trees we know argos owns (crowdsec/, caddy/,
#     backend/, frontend/, docs/, scripts/). Top-level files
#     (docker-compose.override.yml, .env) are protected by
#     explicit excludes; --delete only removes within tracked
#     subtrees.
#   - Idempotent: a no-change run prints "no changes" and exits
#     0 with no rsync invocation.
#   - Refuses to run if SRC or DST aren't both present (no
#     auto-creation of the operational dir).
#
# Usage:
#   ./scripts/sync-prod.sh                     # SRC=script's repo, DST=$ARGOS_PROD_DIR or ~/argos-prod
#   ARGOS_PROD_DIR=/srv/argos-prod ./scripts/sync-prod.sh
#   ./scripts/sync-prod.sh --dry-run           # preview without applying
#   ./scripts/sync-prod.sh --yes               # skip the confirmation prompt
#
# Exit codes:
#   0 = sync succeeded (or no-op)
#   1 = sync diverged or rsync failed
#   2 = setup error (paths missing, rsync absent, etc.)

set -euo pipefail

# Resolve SRC (the repo root) from this script's location so the
# script works wherever the operator invokes it from. DST falls
# back to ~/argos-prod, overridable via env var.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="$(cd "${SCRIPT_DIR}/.." && pwd)"
DST="${ARGOS_PROD_DIR:-${HOME}/argos-prod}"

DRY_RUN=0
YES=0
for arg in "$@"; do
    case "${arg}" in
        --dry-run) DRY_RUN=1 ;;
        --yes|-y)  YES=1 ;;
        --help|-h)
            sed -n '2,/^# Exit codes:/p' "${BASH_SOURCE[0]}"
            exit 0
            ;;
        *)
            echo "[sync-prod] unknown arg: ${arg}" >&2
            echo "[sync-prod] try --help" >&2
            exit 2
            ;;
    esac
done

log()  { printf '[sync-prod] %s\n' "$*"; }
fail() { printf '[sync-prod] FAIL: %s\n' "$*" >&2; exit 1; }
setup_fail() {
    printf '[sync-prod] SETUP: %s\n' "$*" >&2
    exit 2
}

command -v rsync >/dev/null 2>&1 || setup_fail "rsync not installed"

[ -d "${SRC}" ] || setup_fail "source repo missing: ${SRC}"
[ -d "${DST}" ] || setup_fail "operational dir missing: ${DST} (set ARGOS_PROD_DIR or create the dir first)"

# Refuse to clobber the same path -- a misconfigured invocation
# pointing SRC at DST would erase the override file via --delete.
if [ "$(realpath "${SRC}")" = "$(realpath "${DST}")" ]; then
    setup_fail "SRC and DST resolve to the same path; refusing to run"
fi

# The operational dir must look like an argos repo clone, not
# (say) an empty home directory. A top-level docker-compose.yml
# is the cheapest, hardest-to-fake check.
[ -f "${DST}/docker-compose.yml" ] || setup_fail "${DST} does not look like an argos operational dir (no docker-compose.yml)"

# --- exclude list --------------------------------------------
#
# Denylist approach: argos-shipped files sync automatically;
# operator-managed files + build outputs + secrets are protected
# by name. The list is small and reviewable.
#
# A pure allowlist would miss any new top-level file added in a
# future release, so denylist is the right shape here.
EXCLUDES=(
    # Operator-managed files. The override pattern is the
    # documented way to layer prod-specific image pins +
    # port mappings + container names; never overwrite it.
    --exclude='docker-compose.override.yml'
    # Secrets. .env files vary per-deployment; never sync.
    --exclude='.env'
    --exclude='.env.local'
    # Volume / data dirs. Won't be in the repo anyway, but a
    # defensive exclude protects against a misconfigured SRC.
    --exclude='data/'
    --exclude='backups/'
    # VCS state. argos-prod typically isn't a git checkout;
    # if it is, the operator's branch state is theirs.
    --exclude='.git/'
    --exclude='.gitignore'
    # Build outputs / intermediates. Regenerated by
    # docker compose build, no value in syncing. The
    # backend/static/assets path is git-ignored (frontend
    # bundle gets emitted there during the docker multi-
    # stage build); same for frontend/.vite cache.
    --exclude='node_modules/'
    --exclude='dist/'
    --exclude='site/'
    --exclude='frontend/dist/'
    --exclude='frontend/.vite/'
    --exclude='backend/static/assets/'
    --exclude='backend/static/dist/'
    # Local editor / agent state that lives next to the
    # checkout (e.g. .claude/ contains session-local
    # settings; Code IDE workspace configs).
    --exclude='.claude/'
    --exclude='.vscode/'
    --exclude='.idea/'
    # Phase 0 archive + tarballs.
    --exclude='*.tar.gz'
    # Editor / OS noise.
    --exclude='.DS_Store'
    --exclude='*.swp'
    --exclude='*~'
)

# --- diff preview -------------------------------------------
#
# rsync --dry-run --itemize-changes shows the planned operations
# in a one-letter-per-attribute format. We just count the lines
# to detect "nothing to do" and show the operator the full list
# regardless. Operator gets a real preview before any write.

log "SRC: ${SRC}"
log "DST: ${DST}"
log "computing diff (rsync --dry-run)..."
PREVIEW="$(rsync -av --delete --dry-run --itemize-changes "${EXCLUDES[@]}" "${SRC}/" "${DST}/" 2>&1 || true)"
# Filter rsync's status lines so the operator sees only the
# changes (file ops). The status epilogue is preserved at the
# end as a summary block.
CHANGES="$(printf '%s\n' "${PREVIEW}" | grep -E '^[<>cdh\.\*][fdLDS]' || true)"
DELETIONS="$(printf '%s\n' "${PREVIEW}" | grep -E '^deleting ' || true)"

if [ -z "${CHANGES}" ] && [ -z "${DELETIONS}" ]; then
    log "no changes -- ${DST} already in sync with ${SRC}"
    exit 0
fi

echo
echo "=== changes ==="
[ -n "${CHANGES}"   ] && echo "${CHANGES}"
[ -n "${DELETIONS}" ] && echo "${DELETIONS}"
echo
CHANGE_COUNT=$(printf '%s\n' "${CHANGES}" | grep -c . || true)
DELETE_COUNT=$(printf '%s\n' "${DELETIONS}" | grep -c . || true)
log "${CHANGE_COUNT} file(s) to update; ${DELETE_COUNT} deletion(s)"

if [ "${DRY_RUN}" -eq 1 ]; then
    log "dry-run: no changes applied"
    exit 0
fi

if [ "${YES}" -eq 0 ]; then
    if [ ! -t 0 ]; then
        # Stdin is not a TTY (e.g. piped from CI). Refuse to
        # apply silently -- explicit --yes required in non-
        # interactive contexts.
        setup_fail "non-interactive: pass --yes to skip the prompt"
    fi
    printf '[sync-prod] apply these changes to %s? [y/N] ' "${DST}"
    read -r REPLY
    case "${REPLY}" in
        y|Y|yes|YES) ;;
        *) log "aborted"; exit 1 ;;
    esac
fi

log "applying..."
rsync -av --delete "${EXCLUDES[@]}" "${SRC}/" "${DST}/" >/dev/null \
    || fail "rsync failed; the operational dir may be partially synced"

log "PASS: ${DST} synced from ${SRC}"
